import React from 'react';
import { ActivityIndicator, Pressable, ScrollView, StyleSheet, Text, View } from 'react-native';
import { Image } from 'expo-image';
import { useLocalSearchParams, useRouter } from 'expo-router';
import { useQuery } from '@tanstack/react-query';
import { COLORS, RADIUS, SPACING, TYPE, formatMoney } from '@window/shared';
import { api } from '../../src/api/client.js';
import { Icon } from '../../src/components/Icon.js';
import { useLayout } from '../../src/hooks/useLayout.js';

/**
 * The shared-link landing card.
 *
 * A shared link opens as a standalone card with a "keep scrolling" affordance
 * that drops the visitor into a topic-seeded feed. This is the primary organic
 * acquisition path, so the one job this screen has is to make the next scroll
 * irresistible rather than to be a product detail page.
 */
export default function ClusterScreen(): React.ReactElement {
  const router = useRouter();
  const layout = useLayout();
  const { clusterId } = useLocalSearchParams<{ clusterId: string }>();

  const cluster = useQuery({
    queryKey: ['cluster', clusterId],
    queryFn: () => api.cluster(String(clusterId)),
    enabled: Boolean(clusterId),
  });

  const width = layout.columnWidth;

  if (cluster.isLoading) {
    return (
      <View style={styles.centre}>
        <ActivityIndicator color={COLORS.textSecondary} />
      </View>
    );
  }

  if (cluster.isError || !cluster.data) {
    return (
      <View style={styles.centre}>
        <Text style={styles.plain}>That listing is no longer available.</Text>
        <Pressable onPress={() => router.replace('/')} accessibilityRole="button">
          <Text style={styles.action}>Keep scrolling</Text>
        </Pressable>
      </View>
    );
  }

  const data = cluster.data;
  const best = data.offers[0];

  return (
    <View style={styles.root}>
      <Pressable
        onPress={() => router.back()}
        accessibilityRole="button"
        accessibilityLabel="Close"
        style={styles.close}
      >
        <Icon name="close" size={22} />
      </Pressable>

      <ScrollView contentContainerStyle={[styles.content, { width }]}>
        <Image
          source={{ uri: data.media.hero.avif[1] ?? data.media.hero.avif[0] }}
          placeholder={{ blurhash: data.media.hero.blurhash }}
          transition={0}
          contentFit="cover"
          style={{ width, height: width }}
        />

        <View style={styles.body}>
          <Text style={styles.title}>{data.title}</Text>
          {best ? (
            <View style={styles.priceRow}>
              <Text style={styles.price}>{formatMoney(best.landedPrice)}</Text>
              <Text style={styles.secondary}>
                at {best.merchantName}
                {data.offers.length > 1
                  ? ` · ${data.offers.length - 1} other ${
                      data.offers.length === 2 ? 'seller' : 'sellers'
                    }`
                  : ''}
              </Text>
            </View>
          ) : null}

          {data.reviews.count > 0 ? (
            <Text style={styles.secondary}>
              {data.reviews.meanRating?.toFixed(1)} from {data.reviews.count} reviews across{' '}
              {data.reviews.perSource.length}{' '}
              {data.reviews.perSource.length === 1 ? 'source' : 'sources'}
            </Text>
          ) : null}

          {data.reviews.summary ? (
            <View style={styles.summary}>
              {/* Always visibly labelled. It is the only synthesized content
                  anywhere in the product. */}
              <Text style={styles.summaryLabel}>Summary of reviews, generated by a model</Text>
              <Text style={styles.summaryText}>{data.reviews.summary.text}</Text>
            </View>
          ) : null}
        </View>
      </ScrollView>

      <Pressable
        onPress={() => router.replace('/')}
        accessibilityRole="button"
        style={styles.keepScrolling}
      >
        <Text style={styles.keepScrollingText}>Keep scrolling</Text>
      </Pressable>
    </View>
  );
}

const styles = StyleSheet.create({
  root: { flex: 1, backgroundColor: COLORS.surface, alignItems: 'center' },
  centre: {
    flex: 1,
    backgroundColor: COLORS.surface,
    alignItems: 'center',
    justifyContent: 'center',
    gap: 12,
  },
  content: { paddingBottom: 96 },
  plain: { color: COLORS.textPrimary, fontSize: TYPE.sizes.body },
  action: { color: COLORS.accent, fontSize: TYPE.sizes.body, fontWeight: TYPE.weights.semibold },
  body: { padding: SPACING.screenMargin, gap: 8 },
  title: {
    color: COLORS.textPrimary,
    fontSize: TYPE.sizes.body,
    lineHeight: TYPE.lineHeights.body,
  },
  priceRow: { flexDirection: 'row', alignItems: 'baseline', gap: 8, flexWrap: 'wrap' },
  price: {
    color: COLORS.textPrimary,
    fontSize: TYPE.sizes.price,
    lineHeight: TYPE.lineHeights.price,
    fontWeight: TYPE.weights.semibold,
  },
  secondary: { color: COLORS.textSecondary, fontSize: TYPE.sizes.small },
  summary: { gap: 4, marginTop: 8 },
  summaryLabel: {
    color: COLORS.textSecondary,
    fontSize: TYPE.sizes.small,
    textTransform: 'uppercase',
    letterSpacing: 0.6,
  },
  summaryText: {
    color: COLORS.textPrimary,
    fontSize: TYPE.sizes.body,
    lineHeight: TYPE.lineHeights.body,
  },
  close: {
    position: 'absolute',
    top: 16,
    right: 16,
    zIndex: 2,
    width: 44,
    height: 44,
    alignItems: 'center',
    justifyContent: 'center',
  },
  keepScrolling: {
    position: 'absolute',
    bottom: 24,
    minHeight: 48,
    paddingHorizontal: 28,
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: RADIUS.tile,
    backgroundColor: COLORS.accent,
  },
  keepScrollingText: {
    color: COLORS.textPrimary,
    fontSize: TYPE.sizes.body,
    fontWeight: TYPE.weights.semibold,
  },
});
